### ISSUE TITLE
redirect to web application

### ISSUE THREAD

**Issue by MFJoyBoy** [ferronweb/ferron#100]
- domain: example.com
  wwwroot: /var/www/example
  locations:
    - path: "/(.*)"
      wwwroot: var/www/example

i have web application that is hosted in example directory, when i got to example.com/home ferron give me 404
i want ferron to let the web application handle the path (code above not working and that's what i am expect to work)
i'm new to web development

**Comment by MFJoyBoy** [comment]
location / {
  try_files $uri $uri/ /index.html;
}

this is nginx solution

**Comment by DorianNiemiecSVRJS** [comment]
You might try this Ferron YAML configuration to serve the index file in case the server would return 404 Not Found error:

```yaml
hosts:
  - domain: example.com
    wwwroot: /var/www/example
    errorConfig:
      - scode: 404
        rewriteMap:
          - regex: "^/.*"
            replacement: "/"
```

**Comment by DorianNiemiecSVRJS** [comment]
You might also try this configuration (without error configuration), if using static file serving only:

```yaml
hosts:
  - domain: example.com
    wwwroot: /var/www/example
    rewriteMap:
      - regex: "^/.*"
        replacement: "/"
        isNotFile: true
        isNotDirectory: true
```
