### ISSUE TITLE
Question: Is there any forward proxy example?

### ISSUE THREAD

**Issue by fontlos** [ferronweb/ferron#11]
I want to deploy this program on the server to forward proxy a domain to my domain How can I do this?

**Comment by DorianNiemiecSVRJS** [comment]
To use Ferron as a forward proxy, simply enable the `fproxy` module in global configuration:
```yaml
global:
  loadModules:
    - fproxy
```
