### ISSUE TITLE
[Feature Request] Provide a sample Docker Compose file

### ISSUE THREAD

**Issue by ThoriumTextile** [ferronweb/ferron#115]
Greetings.
Like it says on the tin. 
I can try to cook myself up one.
~~_Also the docs don't reference where Ferron reads its config file from._~~
[Here.](https://www.ferronweb.org/docs/installation/installer-linux/)

**Comment by ThoriumTextile** [comment]
Here's a little something that can be worked on:
```
services:
  ferron:
    image: ferronserver/ferron:2
    container_name: myferron
    restart: always
    ports:
      - "80:80"
  # network_mode: host #Optionally uncomment this if you are running already in a container like LXC
    volumes:
      # Configuration bind mount (host file → container)
      - "./config/ferron.yaml:/etc/ferron.yaml"

      # Persistent web root volume
      - "ferron_web:/var/www/ferron"

      # Log directory bind mount (host dir → container)
      - "./logs:/var/log/ferron"

      # Persistent storage for user management data (if used)
      - "ferron_data:/var/lib/ferron"

volumes:
  ferron_web:
  ferron_data:

#Uncomment the following while runnning in bridge mode to add the ferron-proxy network (or any of your liking)
#networks:
 #ferron-proxy:
```
