### ISSUE TITLE
Automatic TLS

### ISSUE THREAD

**Issue by DoctorRyner** [ferronweb/ferron#12]
How about a truly automatic TLS? Like in Caddy. The reason why I daily drive Caddy is it's simplicity, you can start with your application with just ~3 lines in your config and you don't even really need to think about SSL

**Comment by DorianNiemiecSVRJS** [comment]
Currently, automatic TLS in Ferron needs to be explicitly enabled to use it. Also, HTTPS needs to be explicitly enabled to use it.

This is what example configuration for automatic TLS (copied from Ferron's documentation) currently looks like:
```yaml
global:
  secure: true
  enableHTTP2: true # Enable HTTP/2 for improved performance
  enableAutomaticTLS: true
  automaticTLSContactEmail: "someone@example.com" # Replace "someone@example.com" with actual email address
  automaticTLSContactCacheDirectory: "/path/to/letsencrypt-cache" # Replace "/path/to/letsencrypt-cache" with actual cache directory. Optional property, but recommended
  automaticTLSLetsEncryptProduction: true

hosts:
  - domain: "example.com" # Replace "example.com" with your website's domain name
    wwwroot: "/var/www/html"
```

You can read the reference at https://www.ferronweb.org/docs/automatic-tls/.

**Comment by DoctorRainer** [comment]
@DorianNiemiecSVRJS thanks, yes I read the docs :)

I was just wondering about doing more out of the box for the user

**Comment by DorianNiemiecSVRJS** [comment]
The minimal Ferron configuration for automatic TLS (without specifying additional parameters for it) would look like this:

```yaml
global:
  secure: true # Enable HTTPS
  enableAutomaticTLS: true # Enable automatic TLS, without any email notifications or cache

hosts:
  - domain: "example.com" # Replace "example.com" with your website's domain name
    wwwroot: "/var/www/html"
```

The equivalent Caddyfile would look like this:

```caddyfile
# HTTPS and automatic TLS are both enabled by default in Caddy
# Replace "example.com" with your website's domain name
example.com {
  root * /var/www/html
  encode gzip zstd # Enable HTTP compression
  file_server # Serve static files
}
```
