### ISSUE TITLE
Use different certificate for different domains.

### ISSUE THREAD

**Issue by cooperspencer** [ferronweb/ferron#13]
I have a question about different domains. At the moment the example below doesn't work for me because I can't set cert and key for hosts. Did overlook anything?

```
global:
  secure: true
  cert: /path/to/certificate.crt # Replace "/path/to/certificate.crt" to the path to the TLS certificate
  key: /path/to/private.key # Replace "/path/to/private.key" to the path to the private key
  loadModules:
    - rproxy

hosts:
  - domain: foo.example.com
    proxyTo: https://saas.foo.net
  - domain: bar.somethingelse.com
    proxyTo: http://backend.example.net:4000
```

**Comment by DorianNiemiecSVRJS** [comment]
To use different certificates for different domains (if not using automatic TLS), you will have to configure `sni` global configuration property:
```yaml
global:
  secure: true
  cert: /path/to/certificate.crt # Replace "/path/to/certificate.crt" to the path to the TLS certificate
  key: /path/to/private.key # Replace "/path/to/private.key" to the path to the private key
  sni:
    "foo.example.com":
      cert: /path/to/foo-example-com-certificate.crt # Replace "/path/to/foo-example-com-certificate.crt" to the path to the TLS certificate
      key: /path/to/foo-example-com-private.key # Replace "/path/to/foo-example-com-private.key" to the path to the private key
    "bar.somethingelse.com":
      cert: /path/to/bar-somethingelse-com-certificate.crt # Replace "/path/to/bar-somethingelse-com-certificate.crt" to the path to the TLS certificate
      key: /path/to/bar-somethingelse-com-private.key # Replace "/path/to/bar-somethingelse-com-private.key" to the path to the private key
  loadModules:
    - rproxy

hosts:
  - domain: foo.example.com
    proxyTo: https://saas.foo.net
  - domain: bar.somethingelse.com
    proxyTo: http://backend.example.net:4000
```
