### ISSUE TITLE
ASGI support

### ISSUE THREAD

**Issue by alippai** [ferronweb/ferron#2]
Is it in scope to provide ASGI support for eg Starlette? Similar to what nginx unit does.

**Comment by DorianNiemiecSVRJS** [comment]
Well, I would like to use RustPython, but there is a notice on the footer on RustPython's website:

> RustPython is in a development phase and should not be used in production or a fault intolerant setting. Our current build supports only about half of the Python standard library.

There is also PyO3, however I couldn't find the information about statically linked CPython for PyO3.

That said, I could implement ASGI executor as a dynamically linked module that uses a `pyo3` crate.

**Comment by rupurt** [comment]
This would be amazing!

**Comment by DorianNiemiecSVRJS** [comment]
Well, the comment I wrote earlier is a little bit outdated, since I have removed support for dynamically linked modules in Ferron.
That's said, I will implement ASGI executor as an optional module that uses a `pyo3` crate.
However I will postpone this (and other new features) for Ferron 1.1.0, as current priorities for Ferron 1.0.0 are bug fixes, compilance, and security improvements.

**Comment by DorianNiemiecSVRJS** [comment]
I have created a `feature/asgi+wsgi` feature branch, where ASGI and WSGI will be implemented. Currently, I'm focusing on WSGI, and the `wsgi` module is almost completed. I will implement ASGI too.

**Comment by DorianNiemiecSVRJS** [comment]
I have also created a draft pull request (#28) that I will merge once I complete the implementation of both WSGI and ASGI.

**Comment by DorianNiemiecSVRJS** [comment]
I have begun working on ASGI! I have done the first commit related to ASGI - 794255772f952b10877ff3f7cdaef046393e60a9 - which adds a module, which partially implements ASGI.

**Comment by DorianNiemiecSVRJS** [comment]
I have now marked the pull request that adds WSGI and ASGI modules (#28) as ready for review, since it seems like I have completed the implementation of ASGI.

**Comment by DorianNiemiecSVRJS** [comment]
I have now merged the pull request that I mentioned earlier into the `develop` branch. The `wsgi`, `wsgid`, and `asgi` modules are now available on this branch, although they're disabled by default, because they require linking Ferron to an external library (`libpython3.x`). To enable them, compile Ferron with `wsgi`, `wsgid` and `asgi` feature flags (which enable the modules accordingly) using either Cargo or Ferron Forge.
In all modules, the entry point must be available at `application`.

For the `wsgi` module (single-worker), you can configure Ferron like this:
```yaml
global:
  port: 8080
  loadModules:
    - wsgi
  wsgiApplicationPath: /path/to/wsgi/app.py # Replace "/path/to/wsgi/app.py" with the path to the WSGI application, with `application` entry point
```

For the `wsgid` module (with pre-forked process pool), you can configure Ferron like this:
```yaml
global:
  port: 8080
  loadModules:
    - wsgid
  wsgidApplicationPath: /path/to/wsgi/app.py # Replace "/path/to/wsgi/app.py" with the path to the WSGI application, with `application` entry point
```

For the `asgi` module (also single-worker), you can configure Ferron like this:
```yaml
global:
  port: 8080
  loadModules:
    - asgi
  asgiApplicationPath: /path/to/asgi/app.py # Replace "/path/to/asgi/app.py" with the path to the ASGI application, with `application` entry point
```

The next version of Ferron will have these modules available, although disabled by default.
