### ISSUE TITLE
ACME Cache is not used

### ISSUE THREAD

**Issue by Chrystalkey** [ferronweb/ferron#22]
Hi, I have a question or bug report, depending on how this goes: 

I used ferron via it's docker image (version 1.0.0-beta11) and deployed the container with docker-compose. 
This is the relevant compose snippet: 
```yaml
...
ferron:
    image: ferronserver/ferron:latest
    container_name: ferron-app
    restart: unless-stopped
    networks:
      - nginx_network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /srv/ferron/config/ferron.yaml:/etc/ferron.yaml:ro
      - /srv/ferron/webroot:/var/www/ferron:rw
      - /srv/ferron/cache:/var/lecache:rw
      - /srv/ferron/logs:/var/log/ferron:rw
...
```
With lecache being created and writeable in the container (checked via docker exec ferron-app  ls -la /var/lecache).
output: 
```total 8
drwxrwxrwx 2 1000 1000 4096 Apr 11 10:43 .
drwxr-xr-x 1 root root 4096 Apr 11 12:01 ..
```
The sister of it, `/var/log/ferron` is mapped and accessible for writes to the logs as expected, just as `/etc/ferron.yaml` and `/srv/ferron/webroot`.

This is the  configuration snippet of ferron.yaml:
```yaml
...
  secure: true
...
  enableAutomaticTLS: true
  automaticTLSContactEmail: "<whatever@example.com>"
  automaticTLSCacheDirectory: "/var/lecache"
  automaticTLSLetsEncryptProduction: true
...
```

Everything else is working out fine, I set up automatic Cert renewal for six sub servers, but as of now the cache is completely unused, with ferron requesting a new certificate on startup, which is not  really sustainable, especially behind a cloudflare proxy that prevents the challenge from reaching the correct host.

Did I mess up somewhere in the middle? What could be the reason the cache goes unused?
