### ISSUE TITLE
Implement HTTP-01 challenge

### ISSUE THREAD

**Issue by sharf666** [ferronweb/ferron#27]
TLS-ALPN-01 is not feasible where we are behind something like Cloudflare proxy. It would be cool to have alternatives.

**Comment by DorianNiemiecSVRJS** [comment]
Currently, Ferron uses `tokio-rustls-acme` crate for automatic TLS that only supports TLS-ALPN-01 challenge. I have found another crate for automatic TLS - `rustls-acme` - that also supports Tokio and both TLS-ALPN-01 and HTTP-01 challenges, so I might replace `tokio-rustls-acme` with `rustls-acme` crate...

**Comment by DorianNiemiecSVRJS** [comment]
I have replaced the `tokio-rustls-acme` crate with `rustls-acme` crate that can be used to implement HTTP-01 challenge. I did this in the 5656e82216c92efc37d82b3bde9bd5a0c428808e commit. I will soon implement the HTTP-01 challenge...

**Comment by DorianNiemiecSVRJS** [comment]
I have now implemented the HTTP-01 challenge in the 905810db9f7d37c401eb02ae3f8b0608b8a0c998 commit. I tested this over a Cloudflare tunnel, and it works correctly, at least for me.

You can compile Ferron from the "develop" branch, and configure it like this:
```yaml
global:
  secure: true
  enableAutomaticTLS: true
  automaticTLSContactEmail: "someone@example.com" # Replace "someone@example.com" with actual email address
  automaticTLSContactCacheDirectory: "/path/to/letsencrypt-cache" # Replace "/path/to/letsencrypt-cache" with actual cache directory. Optional property, but recommended
  automaticTLSLetsEncryptProduction: true # Use production Let's Encrypt ACME endpoint. If testing, set the property to `false` to use the staging Let's Encrypt ACME endpoint
  useAutomaticTLSHTTPChallenge: true # Use the HTTP-01 challenge instead of the TLS-ALPN-01 challenge

hosts:
  - domain: "example.com" # Replace "example.com" with your website's domain name
    wwwroot: "wwwroot" # Replace "wwwroot" with path to the webroot
```

I have added a new global configuration property - `useAutomaticTLSHTTPChallenge` - which enables the HTTP-01 challenge instead of the TLS-ALPN-01 challenge if set to `true`.

The HTTP-01 challenge will be available in the next version of Ferron.
