### ISSUE TITLE
Feature request: dynamic-upstreams resolve

### ISSUE THREAD

**Issue by git001** [ferronweb/ferron#3]
In today's setup are dynamic resources quite common.

It would be nice to have an DNS resolving similar to the others servers in the market

* HAProxy http://docs.haproxy.org/3.1/configuration.html#5.3
* Caddyserver https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#dynamic-upstreams
* nginx https://nginx.org/en/docs/stream/ngx_stream_upstream_module.html#resolver
* ...

**Comment by DorianNiemiecSVRJS** [comment]
You can use this Ferron configuration:
```yaml
global:
  port: 8080
  loadModules:
   - rproxy
  proxyTo: https://www.ferronweb.org # Replace with a URL you want to proxy requests to
```
And it will proxy to the URL indicated in the configuration.
I tested this configuration on the GNU/Linux build.

![Image](https://github.com/user-attachments/assets/ab237070-5943-4752-ab99-afa4fe0537cd)
