### ISSUE TITLE
Http/3 support?

### ISSUE THREAD

**Issue by symgryph** [ferronweb/ferron#31]
Mostly curious, does farron support quic aka http/3?

**Comment by DorianNiemiecSVRJS** [comment]
Ferron currently doesn't support HTTP/3, nor QUIC.
Hyper (the library for HTTP that Ferron uses), also doesn't currently support HTTP/3, but you can track the hyperium/hyper#1818 issue.
The "hyperium" organization on GitHub (that owns the repository for Hyper) does indeed own `h3` crate (for HTTP/3), but the read-me file says it's still an experimental crate.

**Comment by DorianNiemiecSVRJS** [comment]
I have now added support for HTTP/3 in the 6a531cdff7fb6f4c3e15f6ec503bbd94f52c15c4 commit.
I have tested it myself, and works with `curl` and Chromium-based browsers, but not Mozilla Firefox, so I tracked down the problem, and created the quinn-rs/quinn#2213 issue in Quinn's repository.
To use HTTP/3, you can configure Ferron (you need to compile it from source from `develop` branch) like this:
```yaml
global:
  secure: true
  enableHTTP3: true # HTTP/3 isn't currently enabled by default, since it's experimental in Ferron
  cert: /path/to/certificate.crt # Replace "/path/to/certificate.crt" with path to the TLS certificate
  key: /path/to/private.key # Replace "/path/to/private.key" with path to the private key
```
Also, the `TLS_AES_128_GCM_SHA256` cipher suite must be enabled, otherwise the HTTP/3 server wouldn't start.
The next version of Ferron will include experimental HTTP/3 support.
