### ISSUE TITLE
Having a bit of an issue with a node.js app called planka and reverse proxy

### ISSUE THREAD

**Issue by symgryph** [ferronweb/ferron#35]
All:

I have an external proxy, which is running planka, setup and fine. Here is my config:

```yaml
global:
  logFilePath: /var/log/ferron/access.log
  errorLogFilePath: /var/log/ferron/error.log
  secure: true
  enableHTTP2: true
  enableAutomaticTLS: true
  automaticTLSContactEmail: "someone@somewhere.com" # Replace "someone@example.com" with actual email address
  automaticTLSContactCacheDirectory: "/ferron/letsencrypt-cache" # Replace "/path/to/letsencrypt-cache" with actual cache directory. Optional property, but recommended
  automaticTLSLetsEncryptProduction: true
  loadModules:
    - rproxy

hosts:
  - domain: "my.site.org" # Replace "example.com" with your website's domain name
    proxyTo: "http://localhost:3000"
```

Here is the packet capture (sanitized)

GET / HTTP/1.1
sec-ch-ua: "Chromium";v="135", "Not-A.Brand";v="8"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Linux"
upgrade-insecure-requests: 1
user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
sec-fetch-site: none
sec-fetch-mode: navigate
sec-fetch-user: ?1
sec-fetch-dest: document
accept-encoding: gzip, deflate, br, zstd
accept-language: en-GB,en-US;q=0.9,en;q=0.8
cookie: httpOnlyToken=<REDACTED>; accessTokenVersion=1
if-none-match: <REDACTED>"
priority: u=0, i
host: localhost:3000
connection: keep-alive
x-forwarded-for: 71.142.123.82
x-forwarded-proto: https
x-forwarded-host: my.site.org

HTTP/1.1 304 Not Modified
ETag: W/"56d-miernOHpfoIIb03pe9MzBSg2t8A"
Date: Sat, 03 May 2025 00:29:16 GMT
Connection: keep-alive
Keep-Alive: timeout=5
```
If I go to my.site.org:3000 (the unproxied version) things work fine, and now I get the title page and login, but never get the 'main' pages after I login. The main entry just 'spins'. 

In looking at successful planka configurations (reverse proxy) for nginx, it seems I need to enable websockets support.

Here is a successful nginx config:

```ini
# Planka configuration with CORS and WebSocket support
location /planka {
    proxy_pass http://127.0.0.1:5002;  # <--- use the port you set in your docker-compose.yml
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    # Rewrites URLs to ensure correct handling of the /planka base path
    rewrite ^/planka/(.*)$ /$1 break;

    # Handle WebSocket connections for real-time updates
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";

    # CORS Headers
    add_header 'Access-Control-Allow-Origin' 'http://yourservername';
    add_header 'Access-Control-Allow-Credentials' 'true';
    add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
    add_header 'Access-Control-Allow-Headers' 'Origin, Content-Type, Accept, Authorization, X-Requested-With';

    # Options method for CORS preflight
    if ($request_method = OPTIONS) {
        add_header 'Access-Control-Allow-Origin' 'http://yourservername';
        add_header 'Access-Control-Allow-Credentials' 'true';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'Origin, Content-Type, Accept, Authorization, X-Requested-With';
        return 204;
    }
}
```

Any ideas on this? the main page works, but it seems that the subsequent pages just hang. here is a url for a working config:

https://github.com/plankanban/planka/issues/111

**Comment by DorianNiemiecSVRJS** [comment]
I have reproduced the problem with similar Ferron configuration, but with HTTPS disabled, and followed the Docker installation instructions for Planka at https://docs.planka.cloud/docs/installation/docker/production-version.

I then saw this error message in the error log:
```
[2025-05-03 10:25:22]: Cannot connect to WebSocket server: HTTP error: 400 Bad Request
```

**Comment by DorianNiemiecSVRJS** [comment]
I have probably fixed the issue in the 55be1482afc77467e264dab99ba9474dce316ec8 commit. I think the WebSocket server expected certain HTTP headers, which weren't sent by Ferron reverse proxy, thus returning the 400 Bad Request status code.
The next version of Ferron will probably work with Planka.

**Comment by beckend** [comment]
I am having some problems with WebSocket

<img width="2457" height="1322" alt="Image" src="https://github.com/user-attachments/assets/b45a583b-9f5f-4284-955b-9d164966f8bd" />

With config:
```yaml
global:
  secure: false
  enableHTTP2: true
  enableAutomaticTLS: false
  automaticTLSContactEmail: "someone@example.com"
  automaticTLSContactCacheDirectory: "/var/cache/acme-cache"
  automaticTLSLetsEncryptProduction: false

  loadModules:
    - rproxy

hosts:
  - domain: minio-object-browser.vtdx-enterprise.local
    locations:
      - path: /
        proxyTo: http://minio-object-browser.vtdx.svc.cluster.local:8080
```

The reverse proxy works fine, it's however unable to upgrade the web proxy connection on a sub path.
