### ISSUE TITLE
I hit rate limit for Lets Encrypt really fast

### ISSUE THREAD

**Issue by DoctorRainer** [ferronweb/ferron#37]
[2025-05-05 01:50:21]: Error while obtaining a TLS certificate: order: acme error: http request error: non 2xx http status: 429 "{\n  \"type\": \"urn:ietf:params:acme:error:rateLimited\",\n  \"detail\": \"too many certificates (5) already issued for this exact set of domains in the last 168h0m0s, retry after 2025-05-06 11:04:22 UTC: see https://letsencrypt.org/docs/rate-limits/#new-certificates-per-exact-set-of-hostnames\",\n  \"status\": 429\n}"

With this config.

```
global:
  secure: true
  enableHTTP2: true
  enableAutomaticTLS: true
  automaticTLSContactEmail: ...
  automaticTLSContactCacheDirectory: "/var/letsencrypt-cache"
  automaticTLSLetsEncryptProduction: true
  logFilePath: "/var/log/ferron/access.log"
  errorLogFilePath: "/var/log/ferron/error.log"
  loadModules:
    - rproxy
    - cache
```

Somehow it doesn't happen with caddy. I wonder how they achieved this.

I rebuilt the container a few times.

Do you think it's impossible to prevent this from happening when you want to rebuild your containers?

**Comment by DorianNiemiecSVRJS** [comment]
Have you tried specifying a volume that mounts a directory in the local file system to `/var/letsencrypt-cache` in the container?
I think that when rebuilding a container, any data that's not stored in mounted volumes is lost.

**Comment by DorianNiemiecSVRJS** [comment]
Also, when it comes to `loadModules` property, if you want the proxied responses to be cached, the `cache` module needs to loaded before `rproxy`, like this:
```yaml
global:
  # ...
  loadModules:
    - cache # Load "cache" module before "rproxy" module to cache proxied responses
    - rproxy
```

**Comment by DoctorRainer** [comment]
> Have you tried specifying a volume that mounts a directory in the local file system to `/var/letsencrypt-cache` in the container? I think that when rebuilding a container, any data that's not stored in mounted volumes is lost.

Oh, that makes sense. I think we can come up with a point in documentation that will demonstrate a minimal example of a simple compose.yaml file that demonstrates how to setup caddy so people don't make stupid mistakes I did T-T

I'll test it when my limits reset.

**Comment by DoctorRainer** [comment]
> Also, when it comes to `loadModules` property, if you want the proxied responses to be cached, the `cache` module needs to loaded before `rproxy`, like this:
> 
> global:
>   # ...
>   loadModules:
>     - cache # Load "cache" module before "rproxy" module to cache proxied responses
>     - rproxy

Thanks, now I notice it in the documentation. I just wrongfully assumed that the order doesn't affect anything.

**Comment by DoctorRainer** [comment]
@DorianNiemiecSVRJS I tried adding a volume and confirmed that certificates don't get modified on a rebuild, can you create a new entry in documentation that gives users an example of a compose.yaml file with maybe some explanations? My file right now is like this:

```yaml
name: nebel-monorepo

services:
  server:
    restart: unless-stopped
    image: ferronserver/ferron:1.2.0-alpine
    network_mode: host
    user: root
    volumes:
      - ../server/ferron.yaml:/etc/ferron.yaml
      - ./letsencrypt-cache:/var/letsencrypt-cache
  nebel-sh-frontend:
    restart: unless-stopped
    build:
      context: "../projects/nebel.sh/frontend"
    ports:
      - "8000:8000"
```

Or if you want, I could do those changes to the website myself.
