### ISSUE TITLE
Feature request: include directive

### ISSUE THREAD

**Issue by git001** [ferronweb/ferron#5]
When the config grows and there are several virtual servers grow a single config file very fast.

It would be nice to have a `include <DIR|FILE>` option to separate the config into different locations.

**Comment by DorianNiemiecSVRJS** [comment]
What do you think about the configuration file separation concept below?

Main Ferron configuration (`/etc/ferron.yaml`):
```yaml
include:
  - "/etc/ferron.d/*.yaml" # Load all YAML files in the "/etc/ferron.d" directory specified by a glob
```

Global Ferron configuration (`/etc/ferron.d/global.yaml`):
```yaml
global:
  logFilePath: /var/log/ferron/access.log
  errorLogFilePath: /var/log/ferron/error.log
```

"example.com" host Ferron configuration (`/etc/ferron.d/host-example.yaml`):
```yaml
hosts:
  - domain: example.com
    wwwroot: /var/www/example
```
