### ISSUE TITLE
Feature Request: ForwardAuth

### ISSUE THREAD

**Issue by Richard87** [ferronweb/ferron#6]
Hi, looking forward to see this project moving along!

Is there any plans to include support for Forward Auth?
And forwarding the headers passed to the backend?

Either Nginx style 
https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-subrequest-authentication/

Or Traefik style
https://doc.traefik.io/traefik/middlewares/http/forwardauth/

They have a good illustration of the request-flow:
![Image](https://github.com/user-attachments/assets/21243ccc-63f8-42f5-86d7-2a02e26bc94c)

**Comment by DorianNiemiecSVRJS** [comment]
Thank you!

I have read the Traefik documentation you linked to, and I am thinking of implementing authentication from an external service as a built-in module that can be enabled in the server configuration.

**Comment by DorianNiemiecSVRJS** [comment]
I have now implemented forwarded authentication in the 48921a2ba53d22bbf57eadddb509da9a8aaab526 commit, inspired by Traefik's ForwardAuth middleware.

To use it, you need to first enable the _fauth_ module.

You can use the `authTo` configuration property to set the authentication endpoint.

You can also configure the headers copied from the authentication endpoint's response to the original request.

Example configuration looks like this:

```yaml
global:
  loadModules:
    - fauth
  authTo: http://example.com/auth # Replace with actual authentication endpoint URL.
  forwardedAuthCopyHeaders: # Replace with names of headers you want to copy from the authentication endpoint's response
   - "X-Auth-User"
```

The forwarded authentication will be supported in the next release of Ferron. If you want to try it now, you need to compile Ferron yourself.
