### ISSUE TITLE
reverse proxy  --for example.com --to http://localhost:3000

### ISSUE THREAD

**Issue by stappersg** [ferronweb/ferron#8]
https://www.ferronweb.org/docs/reverse-proxy/ has

```yaml
global:
  loadModules:
    - rproxy
  proxyTo: http://localhost:3000/
```

https://caddyserver.com/docs/quick-starts/reverse-proxy has

You can customize the hostname using the --from flag:

```shell
caddy reverse-proxy --from example.com --to :9000
```

I do read that as _Caddy_ directs requests for `example.com` to port 9000 at localhost.

It is the `--from example.com` part that I miss in the _Ferron_ documentation.

My actual question, what this issue is about:

Has _Ferron_ (or will have _Ferron_) something like:
```yaml
global:
  reverse_proxy:
    - for: example.com/agenda
      to: http://calender.example.net:5000
    - for: example.com
      to: http://localhost:3000/
    - for: bar.example.com
      to: http://backend.example.net:4000
```
So _Ferron_ [multiplexing](https://en.wikipedia.org/wiki/Multiplexing) to several backends.

**Comment by DorianNiemiecSVRJS** [comment]
Yes, you can configure virtual hosts in Ferron to proxy requests to various backend servers like this:

```yaml
global:
  loadModules:
    - rproxy

hosts:
  - domain: example.com
    locations:
      - path: /agenda
        proxyTo: http://calender.example.net:5000 # It proxies /agenda/example to http://calender.example.net/agenda/example. If you want to remove "/agenda" from the request URL supplied to the backend server, you will have to configure URL rewriting
      - path: "/" # Catch-all path
        proxyTo: http://localhost:3000/
  - domain: bar.example.com
    proxyTo: http://backend.example.net:4000
```
